#!/bin/sh

# check firmware is loaded
if [ -z "`xmutil listapps | grep kr260-mv-camera`" ]; then
        echo "
*******************************************************************************
     App not loaded. Please load using \"xmutil loadapp kr260-mv-camera\"
*******************************************************************************
"
        exit;
fi

if [ `xmutil listapps | grep kr260-mv-camera |  awk -F' ' '{ print $6 }'` = "-1" ];
then
        echo "
*******************************************************************************
     App not loaded. Please load using \"xmutil loadapp kr260-mv-camera\"
*******************************************************************************
"
        exit;
fi

# check SFP_LOS signal
GPIO="/sys/class/gpio"
G420="${GPIO}/gpio420"
EXPOR="${GPIO}/export"

if [ ! -d "$G420" ]; then
        echo 420 > ${EXPOR}
fi
val=`cat ${G420}/value`
if [ "$val" = "1" ]; then
        # 10G interface not connected
        echo "
********************************************************************************
     KR260 board is not connected to host machine using SFP+ connector.
      Please connect 10GigE interface in KR260 board to host machine
                to avoid synchronous external abort.
********************************************************************************
        "
        exit
fi

# update eeprom wrapper
APPDIR=/opt/xilinx/xlnx-app-kr260-mv-defect-detect

tmpdir="$(mktemp -d)"
if [ -z "$tmpdir" ]; then
    echo "Couldn't create temp dir" >&2
    exit 1
fi
cleanup() {
    rm -rf "$tmpdir"
}
trap cleanup EXIT

cd "$tmpdir"

ln -s $APPDIR/bin/eeprom.bin
ln -s $APPDIR/bin/xgvrd-kr260.xml
ln -s $APPDIR/bin/gvrd
$APPDIR/bin/update_eeprom
$APPDIR/bin/update_atable gvrd
