#!/bin/sh

APPDIR=/opt/xilinx/xlnx-app-kr260-mv-defect-detect

tmpdir="$(mktemp -d)"
if [ -z "$tmpdir" ]; then
    echo "Couldn't create temp dir" >&2
    exit 1
fi
cleanup() {
    rm -rf "$tmpdir"
}
trap cleanup EXIT

cd "$tmpdir"

ln -s $APPDIR/bin/eeprom.bin
ln -s $APPDIR/bin/xgvrd-kr260.xml
ln -s $APPDIR/bin/gvrd
$APPDIR/bin/update_eeprom
$APPDIR/bin/update_atable gvrd
